camera:
  id: 1
  resolution_width: 640
  resolution_height: 640
  framerate: 30

pipeline:
  yolo_threshold: 0.6
  face_threshold: 0.5
  reid_threshold: 0.60
  faiss_similarity_threshold: 0.58

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "person_counter"

models:
  yolo: "/usr/share/hailo-models/yolov8s_h8l.hef"
  scrfd: "/home/assimilate/models/scrfd_2.5g.hef"
  arcface: "/home/assimilate/models/arcface_mobilefacenet_h8l.hef"
  reid: "/home/assimilate/models/repvgg_a0_person_reid_512.hef"
